name: Glitter Kitten
favicon: null
layout_spectrum: 0
typography_spectrum: 0.22521
title: 'Natural Observations of Ellie Rae & Ms Pookums'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-41224618-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5883b0'
    - '#121011'
    - '#dde3e1'
    - '#45464a'
    - '#9d6c4c'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
