name: Glitter Kitten
favicon: null
layout_spectrum: 0.73562
typography_spectrum: 0.78417
title: Natural Observations of Ellie Rae
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-41224618-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#482c9b'
    - '#160040'
    - '#9f8bbc'
    - '#d5c675'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
